### ISSUE TITLE
Sidebar not really works as expect

### ISSUE THREAD

**Issue by shiho-jo** [shiho-jo/uturano-autograde#12]
![sidebar](https://github.com/user-attachments/assets/9c1bd4de-214f-415e-bcc0-690ea659b222)
It disappears in some of pages.

**Comment by misaka10111** [comment]
This might caused by CORS when you use file:// protocol to open it. If you open the webpages on local web host, the problem should be solved.

**Comment by misaka10111** [comment]
About CORS: "The file:// protocol cannot establish a clear "origin", so the browser treats it as a potential cross-origin request. When an HTML file is loaded via file://, attempting to reference other local files (such as .html, .css, .js, .json, etc.) may be blocked by the browser, which perceives these as cross-origin requests."

**Comment by shiho-jo** [comment]
> How CORS causes the problem: "The file:// protocol cannot establish a clear "origin", so the browser treats it as a potential cross-origin request. When an HTML file is loaded via file://, attempting to reference other local files (such as .html, .css, .js, .json, etc.) may be blocked by the browser, which perceives these as cross-origin requests."

Now works with ngrok server environment. Well done. 
We could conduct tests in virtual machine later on, to improve usability.
