### ISSUE TITLE
Redundant number in settings & Course feature

### ISSUE THREAD

**Issue by shiho-jo** [shiho-jo/uturano-autograde#4]
Should unify the format.
![number](https://github.com/user-attachments/assets/c003a99e-c924-4ffe-bfea-a09bdf75715d)

**Comment by shiho-jo** [comment]
BTW, do we actually need to support multiple courses? Maybe supporting multiple  assignments in a single course is just OK in our prototype implementation.

**Comment by shiho-jo** [comment]
We gonna just support one course, we could keep that, if we decide to let it become a global setting for the course.

**Comment by hhds135** [comment]
I know that.So i will review。

**Comment by shiho-jo** [comment]
> I know that.So i will review。

Right, we can think with that in the next version.
